/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import VariablesGlobales.GlobalVariables;
import conexion.Conexion;
import javax.swing.JOptionPane;
import controlador.ControlEditorial;
import controlador.ControlPrestamo;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import modelo.Editorial;
import java.sql.*;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import modelo.Persona;
import modelo.Prestamo;

/**
 *
 * @author luis_
 */
public class FormMenu extends javax.swing.JFrame {

    DefaultTableModel modelo = new DefaultTableModel();

    Calendar fecha_actual = new GregorianCalendar();
    /**
     * Creates new form FormMenu
     */
    private int idEditorial = 0;
    //private javax.swing.JLabel lblBienvenida;

    //prestamo
    private ControlPrestamo controlPrestamo;

    public FormMenu() {
        initComponents();
        this.setSize(900, 550);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("Menu de Libros y Autores");

        System.out.println("Variables id y nombre" + GlobalVariables.idUsuario + "+" + GlobalVariables.nombreUsuario);

        // Configurar el texto de lblBienvenida aquí
        // lblBienvenida.setText("Bienvenido, " + GlobalVariables.nombreUsuario);
        this.CargarTablaEditorial();

        jTable_Editorial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_EditorialMouseClicked(evt);

            }
        });

        //Para el Prestamo
        jDate_Fecha_actual.setCalendar(fecha_actual);

        // Inicializar controlPrestamo
        controlPrestamo = new ControlPrestamo();

        this.llenarComboBox();
        this.inicializarTablaPrestamos();
        this.cargarNPrestamo();

        DefaultTableModel model = new DefaultTableModel(
                new String[]{"ID Préstamo", "Fecha Préstamo", "Fecha Devolución"}, 0
        );
        jTable_lista_prestamos.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // RELLENAR LOS CAMPOS TXT SELECCIONANDO ALGUN DATO D ELA TABLA 

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton_cerrar_sesion = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel_footer = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel_editorial = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_id_editorial = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField_nombre = new javax.swing.JTextField();
        jButton_limpiar = new javax.swing.JButton();
        jButton_guardar = new javax.swing.JButton();
        jButton_eliminar = new javax.swing.JButton();
        jButton_buscar = new javax.swing.JButton();
        jButton_actualizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Editorial = new javax.swing.JTable();
        jPanel_Prestamos = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel_ = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_lista_titulos = new javax.swing.JTable();
        jTextField_nombre_trabajador = new javax.swing.JTextField();
        jTextField_id_persona_prestamo = new javax.swing.JTextField();
        jTextField_numero_prestamo = new javax.swing.JTextField();
        jTextField_aPaterno_persona_prestamo = new javax.swing.JTextField();
        jTextField_nombre_persona_prestamo = new javax.swing.JTextField();
        jTextField_aMaterno_persona_prestamo = new javax.swing.JTextField();
        jComboBox_titulo_libros = new javax.swing.JComboBox<>();
        jButton_guardar_prestamo = new javax.swing.JButton();
        jButton_quitar_prestamo = new javax.swing.JButton();
        jDate_Fecha_actual = new com.toedter.calendar.JDateChooser();
        jDate_Fecha_devolucion = new com.toedter.calendar.JDateChooser();
        jButton_add_prestamo = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_lista_prestamos = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Menu de Libros y Autores");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 210, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgenes/magia y libro.jpeg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 100, 280, 160));
        jLabel2.getAccessibleContext().setAccessibleDescription("");

        jButton_cerrar_sesion.setBackground(new java.awt.Color(0, 0, 153));
        jButton_cerrar_sesion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_cerrar_sesion.setForeground(new java.awt.Color(255, 255, 255));
        jButton_cerrar_sesion.setText("CERRAR SESION");
        jButton_cerrar_sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cerrar_sesionActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_cerrar_sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 210, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 550));

        jPanel2.setBackground(new java.awt.Color(0, 0, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_footer.setText("Programa por ITS  Luis David Hinojosa Martínez");
        jPanel2.add(jLabel_footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 280, -1));

        jTabbedPane1.setForeground(new java.awt.Color(0, 0, 153));
        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jPanel_editorial.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText("Registro de Editoriales ");
        jPanel_editorial.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 280, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setText("ID Editorial:");
        jPanel_editorial.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 90, 30));

        jTextField_id_editorial.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField_id_editorial.setForeground(new java.awt.Color(0, 0, 153));
        jTextField_id_editorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_id_editorialActionPerformed(evt);
            }
        });
        jTextField_id_editorial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_id_editorialKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_id_editorialKeyTyped(evt);
            }
        });
        jPanel_editorial.add(jTextField_id_editorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 100, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 153));
        jLabel5.setText("Nombre:");
        jPanel_editorial.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 90, 30));

        jTextField_nombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField_nombre.setForeground(new java.awt.Color(0, 0, 153));
        jTextField_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_nombreActionPerformed(evt);
            }
        });
        jTextField_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_nombreKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_nombreKeyTyped(evt);
            }
        });
        jPanel_editorial.add(jTextField_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 110, -1));

        jButton_limpiar.setBackground(new java.awt.Color(0, 0, 102));
        jButton_limpiar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_limpiar.setText("Limpiar");
        jButton_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_limpiarActionPerformed(evt);
            }
        });
        jPanel_editorial.add(jButton_limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 100, -1));

        jButton_guardar.setBackground(new java.awt.Color(0, 0, 102));
        jButton_guardar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_guardar.setText("Guardar");
        jButton_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_guardarActionPerformed(evt);
            }
        });
        jPanel_editorial.add(jButton_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 100, -1));

        jButton_eliminar.setBackground(new java.awt.Color(0, 0, 102));
        jButton_eliminar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_eliminar.setText("Eliminar");
        jButton_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_eliminarActionPerformed(evt);
            }
        });
        jPanel_editorial.add(jButton_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, 100, -1));

        jButton_buscar.setBackground(new java.awt.Color(0, 0, 102));
        jButton_buscar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_buscar.setText("Buscar");
        jButton_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_buscarActionPerformed(evt);
            }
        });
        jPanel_editorial.add(jButton_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 100, -1));

        jButton_actualizar.setBackground(new java.awt.Color(0, 0, 102));
        jButton_actualizar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_actualizar.setText("Actualizar");
        jButton_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_actualizarActionPerformed(evt);
            }
        });
        jPanel_editorial.add(jButton_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, 100, -1));

        jTable_Editorial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_Editorial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_EditorialMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable_EditorialMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Editorial);

        jPanel_editorial.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 370, 260));

        jTabbedPane1.addTab("Editorial", jPanel_editorial);

        jPanel_Prestamos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 153));
        jLabel7.setText("Fecha de devolución:");
        jPanel_Prestamos.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, -1, -1));

        jLabel_.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel_.setForeground(new java.awt.Color(0, 0, 153));
        jLabel_.setText("Prestamos");
        jPanel_Prestamos.add(jLabel_, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, -10, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 153));
        jLabel9.setText("AMaterno:");
        jPanel_Prestamos.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 153));
        jLabel10.setText("N° prestamo: ");
        jPanel_Prestamos.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 153));
        jLabel11.setText("Libros a llevar prestados:");
        jPanel_Prestamos.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 153));
        jLabel12.setText("Nombre del trabajador : ");
        jPanel_Prestamos.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 153));
        jLabel13.setText("APaterno:");
        jPanel_Prestamos.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 153));
        jLabel14.setText("Nombre: ");
        jPanel_Prestamos.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 153));
        jLabel15.setText("Fecha:");
        jPanel_Prestamos.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 153));
        jLabel16.setText("A quien le prestamos: ");
        jPanel_Prestamos.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jTable_lista_titulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_lista_titulos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_lista_titulosMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable_lista_titulosMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_lista_titulos);

        jPanel_Prestamos.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 440, 90));

        jTextField_nombre_trabajador.setBackground(new java.awt.Color(0, 0, 255));
        jTextField_nombre_trabajador.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_nombre_trabajador.setSelectedTextColor(new java.awt.Color(204, 0, 51));
        jTextField_nombre_trabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_nombre_trabajadorActionPerformed(evt);
            }
        });
        jPanel_Prestamos.add(jTextField_nombre_trabajador, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 100, -1));

        jTextField_id_persona_prestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_id_persona_prestamoActionPerformed(evt);
            }
        });
        jTextField_id_persona_prestamo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_id_persona_prestamoKeyTyped(evt);
            }
        });
        jPanel_Prestamos.add(jTextField_id_persona_prestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 200, -1));

        jTextField_numero_prestamo.setBackground(new java.awt.Color(0, 51, 255));
        jTextField_numero_prestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_numero_prestamoActionPerformed(evt);
            }
        });
        jPanel_Prestamos.add(jTextField_numero_prestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 60, -1));

        jTextField_aPaterno_persona_prestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_aPaterno_persona_prestamoActionPerformed(evt);
            }
        });
        jPanel_Prestamos.add(jTextField_aPaterno_persona_prestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 110, -1));

        jTextField_nombre_persona_prestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_nombre_persona_prestamoActionPerformed(evt);
            }
        });
        jPanel_Prestamos.add(jTextField_nombre_persona_prestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 100, -1));

        jTextField_aMaterno_persona_prestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_aMaterno_persona_prestamoActionPerformed(evt);
            }
        });
        jPanel_Prestamos.add(jTextField_aMaterno_persona_prestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 110, -1));

        jComboBox_titulo_libros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona un titulo..." }));
        jComboBox_titulo_libros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_titulo_librosActionPerformed(evt);
            }
        });
        jPanel_Prestamos.add(jComboBox_titulo_libros, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 310, -1));

        jButton_guardar_prestamo.setBackground(new java.awt.Color(0, 0, 102));
        jButton_guardar_prestamo.setForeground(new java.awt.Color(255, 255, 255));
        jButton_guardar_prestamo.setText("Guardar");
        jButton_guardar_prestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_guardar_prestamoActionPerformed(evt);
            }
        });
        jPanel_Prestamos.add(jButton_guardar_prestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, 100, -1));

        jButton_quitar_prestamo.setBackground(new java.awt.Color(0, 0, 102));
        jButton_quitar_prestamo.setForeground(new java.awt.Color(255, 255, 255));
        jButton_quitar_prestamo.setText("Quitar");
        jButton_quitar_prestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_quitar_prestamoActionPerformed(evt);
            }
        });
        jPanel_Prestamos.add(jButton_quitar_prestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, 100, -1));

        jDate_Fecha_actual.setBackground(new java.awt.Color(0, 0, 255));
        jDate_Fecha_actual.setForeground(new java.awt.Color(255, 255, 255));
        jDate_Fecha_actual.setDateFormatString("dd-MMM-yyyy");
        jPanel_Prestamos.add(jDate_Fecha_actual, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, -1, -1));

        jDate_Fecha_devolucion.setBackground(new java.awt.Color(0, 0, 255));
        jDate_Fecha_devolucion.setForeground(new java.awt.Color(255, 255, 255));
        jDate_Fecha_devolucion.setDateFormatString("dd-MMM-yyyy");
        jPanel_Prestamos.add(jDate_Fecha_devolucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, -1, -1));

        jButton_add_prestamo.setBackground(new java.awt.Color(0, 0, 102));
        jButton_add_prestamo.setForeground(new java.awt.Color(255, 255, 255));
        jButton_add_prestamo.setText("Agregar");
        jButton_add_prestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_add_prestamoActionPerformed(evt);
            }
        });
        jPanel_Prestamos.add(jButton_add_prestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 100, -1));

        jTable_lista_prestamos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_lista_prestamos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_lista_prestamosMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable_lista_prestamosMousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(jTable_lista_prestamos);

        jPanel_Prestamos.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 440, 90));

        jTabbedPane1.addTab("Prestamos", jPanel_Prestamos);

        jPanel2.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 600, 430));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Bienvenido ");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 650, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_cerrar_sesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cerrar_sesionActionPerformed
        // TODO add your handling code here:

        System.exit(0);
        System.out.println("Se cerro seción correctamente");
    }//GEN-LAST:event_jButton_cerrar_sesionActionPerformed

    //caja de texto del nombre
    private void jTextField_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_nombreActionPerformed

    //caja de texto del id_editorial
    private void jTextField_id_editorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_id_editorialActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextField_id_editorialActionPerformed

    private void jButton_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_limpiarActionPerformed
        // TODO add your handling code here:
        //con este vamos a limpiar solamente los capos 
        //obtenemos el texto de los campos 
        String id_Text = jTextField_id_editorial.getText().trim();
        String nombre = jTextField_nombre.getText().trim();

        //validamos que no esten vacíos
        if (id_Text.isEmpty() && nombre.isEmpty()) {
            System.out.println("Los campos ya están vacíos");
        } else {
            //si el id esta vacio significa que el nombre si tiene y tenemos que limpiarlo
            jTextField_id_editorial.setText("");
            jTextField_nombre.setText("");
            System.out.println("Los campos se han limpiado correctamente");
        }


    }//GEN-LAST:event_jButton_limpiarActionPerformed

    private void jButton_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_guardarActionPerformed
        // TODO add your handling code here:
        //obtenemos el texto de los campos 
        // String id_Text = jTextField_id_editorial.getText().trim();
        String nombre = jTextField_nombre.getText().trim();

        //validamos que no esten vacíos
        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese el nombre");
        } else {

            //try {
            // Convertir el ID a entero después de la validación
            // int id = Integer.parseInt(id_Text);
            // Aquí puedes continuar con tu lógica, como guardar los datos
            ControlEditorial controlEditorial = new ControlEditorial();
            Editorial editorial = new Editorial();

            //revisar si no hay problema porque es int y no string
            //  editorial.setId_editorial(id);
            editorial.setNombre(nombre);
            //GlobalVariables.idUsuario;

            if (controlEditorial.guardar(editorial)) {
                JOptionPane.showMessageDialog(null, "*** Editorial Registrada   ***");
                //cargar la tabla de vehiculos

                this.CargarTablaEditorial();

                //-----
                //Limpiar campos 
                jTextField_nombre.setText("");
                jTextField_nombre.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "Error al registrar una editorial");
            }

            //} catch (NumberFormatException e) {
            // Manejar el caso en que el ID no sea un número válido
            //JOptionPane.showMessageDialog(null, "El ID debe ser un número válido.");
            //}
        }


    }//GEN-LAST:event_jButton_guardarActionPerformed

    private void jButton_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_eliminarActionPerformed
        // TODO add your handling code here:
        //aqui vamos a querer eliminar uno de los registros
        // Obtener el ID de la editorial y el nombre a eliminar
        String id_Text = jTextField_id_editorial.getText().trim();
        String nombre = jTextField_nombre.getText().trim();

        // Validar que al menos uno de los campos (ID o nombre) esté lleno
        if (id_Text.isEmpty() && nombre.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, ingrese ID o Nombre de la editorial que desea eliminar.");
            return;
        }

        int id_editorial = 0; // Inicializar ID a 0 por defecto
        try {
            if (!id_Text.isEmpty()) {
                id_editorial = Integer.parseInt(id_Text); // Convertir el ID a entero
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "El ID de la editorial debe ser un número válido.");
            return;
        }

        // Confirmar la eliminación
        String mensajeConfirmacion = "¿Está seguro de que desea eliminar la editorial?";
        if (!id_Text.isEmpty()) {
            mensajeConfirmacion += "\nID: " + id_editorial;
        }
        if (!nombre.isEmpty()) {
            mensajeConfirmacion += "\nNombre: " + nombre;
        }
        int confirm = JOptionPane.showConfirmDialog(null, mensajeConfirmacion, "Confirmación", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            // Llamar al método para eliminar la editorial
            ControlEditorial controleditorial = new ControlEditorial();
            boolean eliminado = controleditorial.eliminarEditorial(id_editorial, nombre);

            if (eliminado) {
                JOptionPane.showMessageDialog(null, "La editorial ha sido eliminada exitosamente.");
                this.CargarTablaEditorial(); // Actualizar la tabla
            } else {
                JOptionPane.showMessageDialog(null, "No se pudo eliminar la editorial. Verifique los datos.");
            }
        }
    }//GEN-LAST:event_jButton_eliminarActionPerformed

    private void jButton_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_buscarActionPerformed

        // Manejo de excepciones para convertir el ID
        int id_editorial = 0; // Inicializar a 0 por defecto
        try {
            if (!jTextField_id_editorial.getText().trim().isEmpty()) {
                id_editorial = Integer.parseInt(jTextField_id_editorial.getText().trim());
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "El ID de la editorial debe ser un número entero válido.");
            return;
        }

        String nombre = jTextField_nombre.getText().trim();

        // Validar si no se ingresó ni ID ni nombre
        if (id_editorial <= 0 && nombre.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese ID o Nombre para la búsqueda.");
            this.CargarTablaEditorial(); // Cargar toda la tabla en caso de que no haya búsqueda
        } else {
            // Lógica de búsqueda
            ControlEditorial controleditorial = new ControlEditorial();
            controleditorial.buscarEditorialytodo(id_editorial, nombre);
            ArrayList<Editorial> listaEditoriales = controleditorial.listaEditoriales;

            // Obtener el modelo de la tabla actual para actualizar
            DefaultTableModel model = (DefaultTableModel) jTable_Editorial.getModel();
            model.setRowCount(0); // Limpiar la tabla antes de agregar nuevas filas

            Object fila[] = new Object[2];
            for (Editorial editorial : listaEditoriales) {
                fila[0] = editorial.getId_editorial();
                fila[1] = editorial.getNombre();
                model.addRow(fila); // Agregar cada fila al modelo
            }

            // Actualizar la vista de la tabla
            this.jTable_Editorial.setModel(model);
            this.jScrollPane1.setViewportView(this.jTable_Editorial);
        }

        //Limpiar el texto 
        jTextField_id_editorial.setText("");
        jTextField_nombre.setText("");

    }//GEN-LAST:event_jButton_buscarActionPerformed

    private void jTextField_id_editorialKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_id_editorialKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jTextField_nombre.requestFocus();
        }
    }//GEN-LAST:event_jTextField_id_editorialKeyPressed

    private void jTextField_nombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_nombreKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jButton_guardar.requestFocus();
        }
    }//GEN-LAST:event_jTextField_nombreKeyPressed

    private void jButton_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_actualizarActionPerformed
        // TODO add your handling code here:
        // Obtener el ID de la editorial y el nuevo nombre a actualizar
        String id_Text = jTextField_id_editorial.getText().trim();
        String nuevoNombre = jTextField_nombre.getText().trim();

        // Validar que el ID y el nuevo nombre no estén vacíos
        if (id_Text.isEmpty() || nuevoNombre.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, ingrese tanto el ID como el nuevo nombre para actualizar.");
            return;
        }

        int id_editorial;
        try {
            id_editorial = Integer.parseInt(id_Text); // Convertir el ID a entero
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "El ID de la editorial debe ser un número válido.");
            return;
        }

        int idUsuario = GlobalVariables.idUsuario;

        // Confirmar la actualización
        int confirm = JOptionPane.showConfirmDialog(null, "¿Está seguro de que desea actualizar la editorial con ID " + id_editorial + "?", "Confirmación", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            // Llamar al método para actualizar la editorial
            ControlEditorial controleditorial = new ControlEditorial();
            //boolean actualizado = controleditorial.actualizarEditorial(id_editorial, nuevoNombre);
            boolean actualizado = controleditorial.actualizarEditorial(id_editorial, nuevoNombre, idUsuario);

            if (actualizado) {
                JOptionPane.showMessageDialog(null, "La editorial ha sido actualizada exitosamente.");
                this.CargarTablaEditorial(); // Actualizar la tabla
            } else {
                JOptionPane.showMessageDialog(null, "No se pudo actualizar la editorial. Verifique los datos.");
            }
        }
    }//GEN-LAST:event_jButton_actualizarActionPerformed

    private void jTextField_id_editorialKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_id_editorialKeyTyped
        // TODO add your handling code here:
        char cantidadNumeros = evt.getKeyChar();

        // VALIDA QUE SOLO SEAN NÚMEROS
        if (cantidadNumeros < '0' || cantidadNumeros > '9') {
            evt.consume();  // Detiene la inserción del carácter si no es número
        }

        // LIMITA A UNA LONGITUD DE 5 DÍGITOS
        if (jTextField_id_editorial.getText().length() >= 3) {
            evt.consume();
        }

        // AUTOCOMPLETA CAMPOS MIENTRAS SE TECLEA UNA "ID" EN TIEMPO REAL
        String idBusqueda = jTextField_id_editorial.getText().trim() + evt.getKeyChar();  // Agrega el carácter recién tecleado

        if (!idBusqueda.isEmpty()) {  // Mientras que no sea un texto en blanco en la ID
            for (int i = 0; i < jTable_Editorial.getRowCount(); i++) {
                String idTabla = jTable_Editorial.getValueAt(i, 0).toString();

                if (idBusqueda.equals(idTabla)) {
                    String nombreEditorial = jTable_Editorial.getValueAt(i, 1).toString();
                    jTextField_nombre.setText(nombreEditorial);  // Autocompleta el campo "nombre"
                    break;
                }
            }
        }
    }//GEN-LAST:event_jTextField_id_editorialKeyTyped

    private void jTextField_nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_nombreKeyTyped
        // TODO add your handling code here:
        if (jTextField_nombre.getText().length() >= 10) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_nombreKeyTyped

    private void jTable_EditorialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_EditorialMouseClicked
        // TODO add your handling code here:
        // Obtener la fila seleccionada
        // Comprobar que el evento se está capturando
        System.out.println("Evento mouseClicked capturado");

        // Obtener la fila seleccionada
        int filaSeleccionada = jTable_Editorial.getSelectedRow();

        // Verificar que una fila está seleccionada
        if (filaSeleccionada >= 0) {
            // Mostrar los valores en los JTextFields
            jTextField_id_editorial.setText(jTable_Editorial.getValueAt(filaSeleccionada, 0).toString());
            jTextField_nombre.setText(jTable_Editorial.getValueAt(filaSeleccionada, 1).toString());
            //jTextField_idUsuario.setText(jTable_Editorial.getValueAt(filaSeleccionada, 2).toString());

            // Mensaje de prueba para verificar valores
            System.out.println("ID: " + jTextField_id_editorial.getText());
            System.out.println("Nombre: " + jTextField_nombre.getText());
            //System.out.println("ID Usuario: " + jTextField_idUsuario.getText());
        } else {
            System.out.println("No hay fila seleccionada.");
        }
    }//GEN-LAST:event_jTable_EditorialMouseClicked

    private void jTable_EditorialMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_EditorialMousePressed
        // TODO add your handling code here:
        System.out.println("Ha sido presionado");
        // JOptionPane.showMessageDialog(null, "Ya funciono el pressed");
    }//GEN-LAST:event_jTable_EditorialMousePressed

    private void jTable_lista_titulosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_lista_titulosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable_lista_titulosMouseClicked

    private void jTable_lista_titulosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_lista_titulosMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable_lista_titulosMousePressed

    private void jButton_guardar_prestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_guardar_prestamoActionPerformed
        // TODO add your handling code here:                                           
        // Obtener datos de los campos de texto y fechas
        // Obtener las fechas de los JDateChooser
        java.util.Date fechaPrestamoDate = jDate_Fecha_actual.getDate();
        java.util.Date fechaDevolucionDate = jDate_Fecha_devolucion.getDate();
        int idPersona = Integer.parseInt(jTextField_id_persona_prestamo.getText().trim());

// Validar que los campos no estén vacíos
        if (fechaPrestamoDate == null || idPersona == 0 || jTable_lista_titulos.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Por favor, complete todos los campos obligatorios.");
            System.out.println("Fecha de prestamo " + fechaPrestamoDate);
            System.out.println("Fecha de devolucion " + fechaDevolucionDate);
            System.out.println("Fecha de idPersona " + idPersona);

            return;
        }

// Validar las fechas
        java.sql.Date fechaPrestamo = null;
        java.sql.Date fechaDevolucion = null;
        try {
            // Convertir las fechas de java.util.Date a java.sql.Date
            fechaPrestamo = new java.sql.Date(fechaPrestamoDate.getTime());
            if (fechaDevolucionDate != null) {
                fechaDevolucion = new java.sql.Date(fechaDevolucionDate.getTime());
                if (fechaDevolucion.before(fechaPrestamo)) {
                    JOptionPane.showMessageDialog(null, "La fecha de devolución no puede ser anterior a la fecha del préstamo.");
                    return;
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al procesar las fechas. Verifique los valores seleccionados.");
            return;
        }

        // Obtener los títulos de los libros desde el JTable
        List<String> titulosLibros = new ArrayList<>();
        for (int i = 0; i < jTable_lista_titulos.getRowCount(); i++) {
            titulosLibros.add(jTable_lista_titulos.getValueAt(i, 0).toString());
        }

        // Lógica para guardar los datos en la base de datos
        ControlPrestamo controlPrestamo = new ControlPrestamo();
        if (controlPrestamo.guardarPrestamo(fechaPrestamo, fechaDevolucion, idPersona, titulosLibros)) {
            JOptionPane.showMessageDialog(null, "Préstamo registrado correctamente.");
            //this.CargarTablaPrestamos(); // Si tienes una tabla de préstamos, actualízala
            cargarNPrestamo();
            jTextField_id_persona_prestamo.setText("");
            // Limpiar los campos si no se encuentra la persona

            jTextField_nombre_persona_prestamo.setText("");
            jTextField_aPaterno_persona_prestamo.setText("");
            jTextField_aMaterno_persona_prestamo.setText("");
            jTextField_id_persona_prestamo.setText("");

            jDate_Fecha_devolucion.setDate(null);

            // Limpiar la tabla y mostrar mensaje
            DefaultTableModel model = (DefaultTableModel) jTable_lista_prestamos.getModel();
            model.setRowCount(0);

            // Limpiar la tabla y mostrar mensaje
            DefaultTableModel modelito = (DefaultTableModel) jTable_lista_titulos.getModel();
            modelito.setRowCount(0);

        } else {
            JOptionPane.showMessageDialog(null, "Error al registrar el préstamo.");
        }


    }//GEN-LAST:event_jButton_guardar_prestamoActionPerformed

    private void jTextField_nombre_trabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_nombre_trabajadorActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextField_nombre_trabajadorActionPerformed

    private void jTextField_id_persona_prestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_id_persona_prestamoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextField_id_persona_prestamoActionPerformed

    private void jTextField_numero_prestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_numero_prestamoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_numero_prestamoActionPerformed

    private void jTextField_aPaterno_persona_prestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_aPaterno_persona_prestamoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_aPaterno_persona_prestamoActionPerformed

    private void jTextField_nombre_persona_prestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_nombre_persona_prestamoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_nombre_persona_prestamoActionPerformed

    private void jTextField_aMaterno_persona_prestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_aMaterno_persona_prestamoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_aMaterno_persona_prestamoActionPerformed

    private void jButton_quitar_prestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_quitar_prestamoActionPerformed
        // TODO add your handling code here:

        // Obtener el modelo de la tabla
        DefaultTableModel model = (DefaultTableModel) jTable_lista_titulos.getModel();

        // Verificar si hay una fila seleccionada
        int selectedRow = jTable_lista_titulos.getSelectedRow();
        if (selectedRow == -1) {
            // Mostrar un mensaje si no hay ninguna fila seleccionada
            JOptionPane.showMessageDialog(null, "Por favor, seleccione un título de la lista para quitar.");
            return;
        }

        // Confirmación antes de eliminar
        int confirm = JOptionPane.showConfirmDialog(
                null,
                "¿Está seguro de que desea quitar el título seleccionado?",
                "Confirmación",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm == JOptionPane.YES_OPTION) {
            // Eliminar la fila seleccionada del modelo
            model.removeRow(selectedRow);
            JOptionPane.showMessageDialog(null, "Título quitado de la lista.");
        }


    }//GEN-LAST:event_jButton_quitar_prestamoActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        // TODO add your handling code here:

        System.out.println("Panel de préstamos enfocado");

        setDato(GlobalVariables.nombreUsuario);
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void jComboBox_titulo_librosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_titulo_librosActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jComboBox_titulo_librosActionPerformed

    private void jTextField_id_persona_prestamoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_id_persona_prestamoKeyTyped
        // TODO add your handling code here:
        char cantidadNumeros = evt.getKeyChar();

        // VALIDA QUE SOLO SEAN NÚMEROS
        if (cantidadNumeros < '0' || cantidadNumeros > '9') {
            evt.consume();  // Detiene la inserción del carácter si no es número
        }

        // LIMITA A UNA LONGITUD DE 3 DÍGITOS
        if (jTextField_id_persona_prestamo.getText().length() >= 3) {
            evt.consume();
            return;
        }

        // CONSTRUIMOS EL ID COMPLETO (AGREGANDO EL NUEVO CARÁCTER)
        String idBusqueda = jTextField_id_persona_prestamo.getText() + cantidadNumeros;

        // BUSCAMOS A LA PERSONA EN LA BASE DE DATOS
        ControlPrestamo control = new ControlPrestamo();
        Persona persona = control.buscarPersonaPorId(idBusqueda);

        // VALIDAR SI LA PERSONA EXISTE
        if (persona != null) {
            // SI EXISTE, MOSTRAR INFORMACIÓN EN CONSOLA
            System.out.println("La persona encontrada es: " + persona.toString());

            jTextField_nombre_persona_prestamo.setText(persona.getNombre());
            jTextField_aPaterno_persona_prestamo.setText(persona.getaPaterno());
            jTextField_aMaterno_persona_prestamo.setText(persona.getaMaterno());

            List<Prestamo> prestamos = control.buscarPrestamosPorPersona(persona.getId_persona());

            if (!prestamos.isEmpty()) {
                // Mostrar los préstamos en la tabla
                DefaultTableModel model = (DefaultTableModel) jTable_lista_prestamos.getModel();
                model.setRowCount(0); // Limpiar la tabla
                for (Prestamo prestamo : prestamos) {
                    model.addRow(new Object[]{prestamo.getId_prestamo(), prestamo.getFecha_prestamo(), prestamo.getFecha_devolucion()});
                }
            } else {
                // Limpiar la tabla y mostrar mensaje
                DefaultTableModel model = (DefaultTableModel) jTable_lista_prestamos.getModel();
                model.setRowCount(0);
                JOptionPane.showMessageDialog(this, "El usuario no tiene préstamos registrados.");
            }

//            if (tiene  {
//                prestamo
//            }
//            
//                ){
//                mostrarla en la tabla 
//            }else{
//                        mostrar en la tabla sin prestamos
//                    }
        } else {
            // SI NO EXISTE, MOSTRAR UN MENSAJE
            JOptionPane.showMessageDialog(
                    this, // Ventana actual
                    "La persona con el ID " + idBusqueda + " no existe en la base de datos.", // Mensaje
                    "Persona no encontrada", // Título del cuadro
                    JOptionPane.WARNING_MESSAGE // Tipo de mensaje
            );
            // Limpiar los campos si no se encuentra la persona

            jTextField_nombre_persona_prestamo.setText("");
            jTextField_aPaterno_persona_prestamo.setText("");
            jTextField_aMaterno_persona_prestamo.setText("");
            jTextField_id_persona_prestamo.setText("");
        }
        System.out.println("El string dice:" + idBusqueda);


    }//GEN-LAST:event_jTextField_id_persona_prestamoKeyTyped

    private void jButton_add_prestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_add_prestamoActionPerformed
        // TODO add your handling code here:

        // Obtener el texto seleccionado del JComboBox
        String tituloSeleccionado = (String) jComboBox_titulo_libros.getSelectedItem();

        // Validar que haya un título seleccionado
        if (tituloSeleccionado == null || tituloSeleccionado.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, seleccione un título.");
            return;
        }

        // Agregar el título al modelo del JTable
        DefaultTableModel model = (DefaultTableModel) jTable_lista_titulos.getModel();

        for (int i = 0; i < model.getRowCount(); i++) {
            if (model.getValueAt(i, 0).equals(tituloSeleccionado)) {
                JOptionPane.showMessageDialog(null, "El título ya está en la lista.");
                return;
            }
        }

        // Agregar el título al modelo del JTable
        model.addRow(new Object[]{tituloSeleccionado});

        // Limpiar la selección del JComboBox (opcional)
        jComboBox_titulo_libros.setSelectedIndex(0);

        // Confirmación
        JOptionPane.showMessageDialog(null, "Título agregado a la lista.");


    }//GEN-LAST:event_jButton_add_prestamoActionPerformed

    private void jTable_lista_prestamosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_lista_prestamosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable_lista_prestamosMouseClicked

    private void jTable_lista_prestamosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_lista_prestamosMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable_lista_prestamosMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_actualizar;
    private javax.swing.JButton jButton_add_prestamo;
    private javax.swing.JButton jButton_buscar;
    private javax.swing.JButton jButton_cerrar_sesion;
    private javax.swing.JButton jButton_eliminar;
    private javax.swing.JButton jButton_guardar;
    private javax.swing.JButton jButton_guardar_prestamo;
    private javax.swing.JButton jButton_limpiar;
    private javax.swing.JButton jButton_quitar_prestamo;
    private javax.swing.JComboBox<String> jComboBox_titulo_libros;
    private com.toedter.calendar.JDateChooser jDate_Fecha_actual;
    private com.toedter.calendar.JDateChooser jDate_Fecha_devolucion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_;
    private javax.swing.JLabel jLabel_footer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel_Prestamos;
    private javax.swing.JPanel jPanel_editorial;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable_Editorial;
    private javax.swing.JTable jTable_lista_prestamos;
    private javax.swing.JTable jTable_lista_titulos;
    private javax.swing.JTextField jTextField_aMaterno_persona_prestamo;
    private javax.swing.JTextField jTextField_aPaterno_persona_prestamo;
    private javax.swing.JTextField jTextField_id_editorial;
    private javax.swing.JTextField jTextField_id_persona_prestamo;
    private javax.swing.JTextField jTextField_nombre;
    private javax.swing.JTextField jTextField_nombre_persona_prestamo;
    private javax.swing.JTextField jTextField_nombre_trabajador;
    private javax.swing.JTextField jTextField_numero_prestamo;
    // End of variables declaration//GEN-END:variables

    //metodo para mostrar las editoriales 
    private void CargarTablaEditorial() {
        Connection cn = Conexion.connectar();
        DefaultTableModel model = new DefaultTableModel();
        String sql = "SELECT id_editorial, nombre, id_usuario FROM editorial;";
        Statement st;
        try {
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            this.jTable_Editorial = new JTable(model);
            this.jScrollPane1.setViewportView(this.jTable_Editorial);

            model.addColumn("N°");
            model.addColumn("Nombre");
            model.addColumn("Id Usuario");

            while (rs.next()) {
                Object fila[] = new Object[3];
                for (int i = 0; i < 3; i++) {
                    fila[i] = rs.getObject(i + 1);

                }
                model.addRow(fila);
            }

        } catch (SQLException e) {
            System.out.println("Error al llenar la tabla de editorial: " + e);
        }
    }

    //Metodos para el Prestamo
    public void setDato(String dato) {
        GlobalVariables.nombreUsuario = dato;
        System.out.println("El dato es: " + dato);
        jTextField_nombre_trabajador.setText(dato);
    }

    private void llenarComboBox() {
        ArrayList<String> titulos = controlPrestamo.obtenerTitulosDeLibros();
        if (titulos.isEmpty()) {
            jComboBox_titulo_libros.addItem("No hay libros disponibles");
        } else {
            for (String titulo : titulos) {
                jComboBox_titulo_libros.addItem(titulo);
            }
        }
    }

    private void inicializarTablaPrestamos() {
    // Crear un modelo con solo una columna "Título"
    DefaultTableModel model = new DefaultTableModel(new Object[]{"Título"}, 0) {
        @Override
        public boolean isCellEditable(int row, int column) {
            // Hacer que las celdas no sean editables
            return false;
        }
    };

    // Asignar el modelo al JTable
    jTable_lista_titulos.setModel(model);

    // Ajustar el ancho de la columna "Título" para mejor apariencia
    jTable_lista_titulos.getColumnModel().getColumn(0).setPreferredWidth(200);

    // Deshabilitar el reordenamiento de columnas
    jTable_lista_titulos.getTableHeader().setReorderingAllowed(false);
}

    


    // Este código debe estar en el lugar donde tienes el botón o la acción de cargar el próximo ID en el JTextField.
    private void cargarNPrestamo() {
        // Crear una instancia de la clase ControlPrestamo
        ControlPrestamo controlPrestamo = new ControlPrestamo();

        // Llamar al método para obtener el próximo ID de préstamo
        int nextId = controlPrestamo.obtenerProximoIdPrestamo();

        // Asignar el valor al JTextField correspondiente
        jTextField_numero_prestamo.setText(String.valueOf(nextId));
    }

}
