/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JOptionPane;
import controlador.ControlEditorial;
import modelo.Editorial;

/**
 *
 * @author luis_
 */
public class FormMenu extends javax.swing.JFrame {

    /**
     * Creates new form FormMenu
     */
    public FormMenu() {
        initComponents();
        this.setSize(900, 550);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("Menu de Libros y Autores");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton_cerrar_sesion = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel_footer = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel_editorial = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_id_editorial = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField_nombre = new javax.swing.JTextField();
        jButton_limpiar = new javax.swing.JButton();
        jButton_guardar = new javax.swing.JButton();
        jButton_eliminar = new javax.swing.JButton();
        jButton_buscar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Menu de Libros y Autores");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 210, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgenes/magia y libro.jpeg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 100, 280, 160));
        jLabel2.getAccessibleContext().setAccessibleDescription("");

        jButton_cerrar_sesion.setBackground(new java.awt.Color(0, 0, 153));
        jButton_cerrar_sesion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_cerrar_sesion.setForeground(new java.awt.Color(255, 255, 255));
        jButton_cerrar_sesion.setText("CERRAR SESION");
        jButton_cerrar_sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cerrar_sesionActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_cerrar_sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 210, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 550));

        jPanel2.setBackground(new java.awt.Color(0, 0, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_footer.setText("Programa ITS");
        jPanel2.add(jLabel_footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 110, -1));

        jTabbedPane1.setForeground(new java.awt.Color(0, 0, 153));

        jPanel_editorial.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText("Registro de Editoriales ");
        jPanel_editorial.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 280, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setText("ID Editorial:");
        jPanel_editorial.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 90, 30));

        jTextField_id_editorial.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField_id_editorial.setForeground(new java.awt.Color(0, 0, 153));
        jTextField_id_editorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_id_editorialActionPerformed(evt);
            }
        });
        jPanel_editorial.add(jTextField_id_editorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 230, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 153));
        jLabel5.setText("Nombre:");
        jPanel_editorial.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 90, 30));

        jTextField_nombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField_nombre.setForeground(new java.awt.Color(0, 0, 153));
        jTextField_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_nombreActionPerformed(evt);
            }
        });
        jPanel_editorial.add(jTextField_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 230, -1));

        jButton_limpiar.setBackground(new java.awt.Color(0, 0, 102));
        jButton_limpiar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_limpiar.setText("Limpiar");
        jButton_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_limpiarActionPerformed(evt);
            }
        });
        jPanel_editorial.add(jButton_limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 100, -1));

        jButton_guardar.setBackground(new java.awt.Color(0, 0, 102));
        jButton_guardar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_guardar.setText("Guardar");
        jButton_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_guardarActionPerformed(evt);
            }
        });
        jPanel_editorial.add(jButton_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 100, -1));

        jButton_eliminar.setBackground(new java.awt.Color(0, 0, 102));
        jButton_eliminar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_eliminar.setText("Eliminar");
        jButton_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_eliminarActionPerformed(evt);
            }
        });
        jPanel_editorial.add(jButton_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 100, -1));

        jButton_buscar.setBackground(new java.awt.Color(0, 0, 102));
        jButton_buscar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_buscar.setText("Buscar");
        jButton_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_buscarActionPerformed(evt);
            }
        });
        jPanel_editorial.add(jButton_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 280, 100, -1));

        jTabbedPane1.addTab("Editorial", jPanel_editorial);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 345, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab2", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 345, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab3", jPanel5);

        jPanel2.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 600, 380));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 650, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_cerrar_sesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cerrar_sesionActionPerformed
        // TODO add your handling code here:
        
        System.exit(0);
        System.out.println("Se cerro seción correctamente");
    }//GEN-LAST:event_jButton_cerrar_sesionActionPerformed

    private void jTextField_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_nombreActionPerformed

    private void jTextField_id_editorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_id_editorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_id_editorialActionPerformed

    private void jButton_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_limpiarActionPerformed
        // TODO add your handling code here:
        //con este vamos a limpiar solamente los capos 
        //obtenemos el texto de los campos 
        String id_Text = jTextField_id_editorial.getText().trim();
        String nombre = jTextField_nombre.getText().trim();

        //validamos que no esten vacíos
        if ( id_Text.isEmpty() || nombre.isEmpty()) {
            System.out.println("Ya estan vacias");
        } else {
            //si el id esta vacio significa que el nombre si tiene y tenemos que limpiarlo
            jTextField_id_editorial.setText("");
            jTextField_nombre.setText("");
            System.out.println("Ya se limpio");
        }
           
        
    }//GEN-LAST:event_jButton_limpiarActionPerformed

    private void jButton_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_guardarActionPerformed
        // TODO add your handling code here:
        //obtenemos el texto de los campos 
       // String id_Text = jTextField_id_editorial.getText().trim();
        String nombre = jTextField_nombre.getText().trim();

        //validamos que no esten vacíos
        if ( nombre.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese el nombre");
        } else {
            
            //try {
                // Convertir el ID a entero después de la validación
               // int id = Integer.parseInt(id_Text);

                // Aquí puedes continuar con tu lógica, como guardar los datos
                ControlEditorial controlEditorial = new ControlEditorial();
                Editorial editorial = new Editorial();

                //revisar si no hay problema porque es int y no string
              //  editorial.setId_editorial(id);
                editorial.setNombre(nombre);
                
                if (controlEditorial.guardar(editorial)) {
                    JOptionPane.showMessageDialog(null, "*** Editorial Registrada   ***");
                    //cargar la tabla de vehiculos

                    //-----
                    //Limpiar campos 
                    jTextField_nombre.setText("");
                    jTextField_nombre.setText("");
                } else {
                    JOptionPane.showMessageDialog(null, "Error al registrar una editorial");
                }
                
            //} catch (NumberFormatException e) {
                // Manejar el caso en que el ID no sea un número válido
                JOptionPane.showMessageDialog(null, "El ID debe ser un número válido.");
            //}
        }
        

    }//GEN-LAST:event_jButton_guardarActionPerformed

    private void jButton_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_eliminarActionPerformed
        // TODO add your handling code here:
        //aqui vamos a querer eliminar uno de los registros
    }//GEN-LAST:event_jButton_eliminarActionPerformed

    private void jButton_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_buscarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton_buscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_buscar;
    private javax.swing.JButton jButton_cerrar_sesion;
    private javax.swing.JButton jButton_eliminar;
    private javax.swing.JButton jButton_guardar;
    private javax.swing.JButton jButton_limpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_footer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel_editorial;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField_id_editorial;
    private javax.swing.JTextField jTextField_nombre;
    // End of variables declaration//GEN-END:variables
}
